# Generated by Django 5.2.4 on 2025-10-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueDescriptive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_colonne', models.CharField(max_length=255)),
                ('nb_valeurs_manquantes', models.IntegerField()),
                ('nb_valeurs_non_manquantes', models.IntegerField()),
                ('type_colonne', models.CharField(choices=[('num', 'Numérique'), ('cat', 'Catégorielle'), ('date', 'Date')], max_length=10)),
                ('min_val', models.FloatField(blank=True, null=True)),
                ('max_val', models.FloatField(blank=True, null=True)),
                ('moyenne', models.FloatField(blank=True, null=True)),
                ('skewness', models.FloatField(blank=True, null=True)),
                ('mediane', models.FloatField(blank=True, null=True)),
                ('mode_val', models.CharField(blank=True, max_length=255, null=True)),
                ('ecart_type', models.FloatField(blank=True, null=True)),
                ('kurtosis', models.FloatField(blank=True, null=True)),
                ('variance', models.FloatField(blank=True, null=True)),
                ('etendue', models.FloatField(blank=True, null=True)),
                ('distribution', models.JSONField(blank=True, null=True)),
                ('quartile', models.JSONField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('nb_categories_uniques', models.IntegerField(blank=True, null=True)),
                ('frequence', models.JSONField(blank=True, null=True)),
                ('premiere_date', models.DateTimeField(blank=True, null=True)),
                ('derniere_date', models.DateTimeField(blank=True, null=True)),
                ('intervalle_total', models.CharField(blank=True, max_length=255, null=True)),
                ('frequence_par_periode', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
